package livezone

import (
	"encoding/json"
	"fmt"
	"strings"
	"testing"

	"github.com/dobbo-ca/headroom-go/internal/router"
	"github.com/dobbo-ca/headroom-go/internal/tokenizer"
	"github.com/dobbo-ca/headroom-go/internal/toolpairs"
)

// proseBlock is prose long enough for the crusher to act on.
func proseBlock() string {
	var b strings.Builder
	for i := 0; i < 60; i++ {
		fmt.Fprintf(&b, "Line %d of the document explains a separate consideration in detail.\n", i)
	}
	return b.String()
}

// bodyWith wraps text as a tool_result produced by the named tool.
func toolBody(t *testing.T, tool, command, text string) []byte {
	t.Helper()
	quoted, err := json.Marshal(text)
	if err != nil {
		t.Fatal(err)
	}
	input := `{}`
	if command != "" {
		c, err := json.Marshal(command)
		if err != nil {
			t.Fatal(err)
		}
		input = `{"command":` + string(c) + `}`
	}
	return []byte(`{"model":"claude-sonnet-5","messages":[` +
		`{"role":"user","content":[{"type":"text","text":"go"}]},` +
		`{"role":"assistant","content":[{"type":"tool_use","id":"t1","name":"` + tool + `","input":` + input + `}]},` +
		`{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":` + string(quoted) + `}]}]}`)
}

func dispatchWith(t *testing.T, body []byte) Result {
	t.Helper()
	return Dispatch(body, Options{
		Router:      router.NewDefault(),
		Store:       newMapStore(),
		Tokenizer:   tokenizer.GetTokenizer("claude"),
		FrozenCount: 0,
	})
}

// The whole safety case for TextCrusher. Raw file content must come back
// byte-for-byte: the agent needs exact bytes to produce a precise patch, and
// dropping sentences from it was observed upstream to cause re-reads and wrong
// resolutions. Derived output has no such constraint.
func TestProtectedReadsAreNeverCrushed(t *testing.T) {
	text := proseBlock()

	// CONTROL FIRST. The same bytes from a derived command MUST compress, or
	// every "was not compressed" assertion below is vacuous.
	derived := dispatchWith(t, toolBody(t, "Bash", "grep -rn foo .", text))
	if !derived.Applied {
		t.Fatalf("derived output was not compressed (reason %q); the protection "+
			"assertions below would prove nothing", derived.Reason)
	}

	protected := []struct{ name, tool, cmd string }{
		{"Read tool", "Read", ""},
		{"bash cat", "Bash", "cat notes.md"},
		{"bash sed range", "Bash", "sed -n '1,80p' server.rb"},
		{"bash head", "Bash", "head -100 schema.sql"},
		{"rtk-wrapped cat", "Bash", "rtk cat notes.md"},
		{"cd then cat", "Bash", "cd /tmp/x && cat notes.md"},
	}
	for _, tt := range protected {
		t.Run(tt.name, func(t *testing.T) {
			body := toolBody(t, tt.tool, tt.cmd, text)
			res := dispatchWith(t, body)
			if res.Applied {
				t.Errorf("a protected file read was rewritten: %d bytes in, %d out",
					len(body), len(res.Body))
			}
			if string(res.Body) != string(body) {
				t.Error("the forwarded bytes differ from what arrived")
			}
		})
	}
}

// A lockfile is regenerated by a tool and never byte-patched, so a read of one
// stays compressible even though it reads as plain text.
func TestLockfileReadsStayCompressible(t *testing.T) {
	res := dispatchWith(t, toolBody(t, "Bash", "cat go.sum", proseBlock()))
	if !res.Applied {
		t.Errorf("a lockfile read was protected; it is regenerated, never patched (reason %q)", res.Reason)
	}
}

// The index is what makes any of this possible. Without it every block looks
// like it came from an unknown tool.
func TestToolUseIndexResolvesTheProducer(t *testing.T) {
	body := toolBody(t, "Bash", "cat notes.md", "hello")
	idx := toolpairs.Index(body)
	u, ok := idx["t1"]
	if !ok {
		t.Fatal("tool_use_id t1 did not resolve")
	}
	if u.Name != "Bash" {
		t.Errorf("name = %q, want Bash", u.Name)
	}
	if !strings.Contains(u.Input, "cat notes.md") {
		t.Errorf("input = %q, want the command", u.Input)
	}
}

// An unresolvable id must not be read as "safe". It yields an unknown producer,
// and an unknown producer is not a read — but it also must not crash.
func TestUnresolvableToolUseIDIsHandled(t *testing.T) {
	body := []byte(`{"model":"m","messages":[` +
		`{"role":"user","content":[{"type":"tool_result","tool_use_id":"missing","content":"short"}]}]}`)
	res := dispatchWith(t, body)
	if res.Body == nil {
		t.Fatal("Dispatch returned no body")
	}
}
